pipeline{
   agent any 
   tools{
    maven'M2_HOME'
   }
   stages{
    stage('sonar-scan'){
        steps{
            sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=hyvrane_geo1'
        }
    }
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
             target/bio*.jar \
              "http://ec2-100-24-242-154.compute-1.amazonaws.com:8081/artifactory/geolocation/bio_${BUILD_ID}.jar"'
        }
    }
   }
}
