pipeline{
   agent any 
   tools{
    maven'M2_HOME'
   }
   stages{
    stage('sonar-scan'){
        steps{
            withSonarQubeEnv('sonarQube'){
                 sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=hyvrane_geo1'

            }
           
        }
    }
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
             target/bio*.jar \
              "http://52.205.99.30:8081/artifactory/geolocation/bio_${BUILD_ID}.jar"'
        }
    }
    stage('docker login'){
        steps{
            sh 'aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin \
            157053284586.dkr.ecr.us-east-1.amazonaws.com'
        }
    }
    stage('docker image build'){
        steps{
            sh 'docker build -t utc-app-dev:v.${BUILD_ID} .'
        }
    }
    stage('image tagging'){
        steps{
            sh 'docker tag utc-app-dev:v.${BUILD_ID} \
            157053284586.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
            //sh 'docker tag utc-app-dev:latest \
           // 157053284586.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
        }
    }
    stage('push image to ecr'){
        steps{
            sh 'docker push 157053284586.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
            sh 'docker push 157053284586.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
        }
    }
   }
}
